version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sykell_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sykell_url_analyzer
      MYSQL_USER: sykell_user
      MYSQL_PASSWORD: sykell_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
